config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admins
  root "home#index"
  get 'city/:city' => 'inns#by_city', as: 'by_city'
  resources :inns, only: [:show, :new, :create, :edit, :update] do
    delete 'delete_photo/:photo_id', to: 'inns#delete_photo', as: 'delete_photo', on: :member
    resources :ratings, only: [:index]
    get :search, on: :collection
    resources :rooms, only: [:show, :new, :create, :edit, :update] do
      resources :price_customizations, only: [:new, :create, :edit, :update]
      post :available, on: :member
      post :unavailable, on: :member
    end
    post :active, on: :member
    post :inactive, on: :member
    get :admin_show, on: :member
  end
  resources :rooms, only: [:index] do
    delete 'delete_photo/:photo_id', to: 'rooms#delete_photo', as: 'delete_photo', on: :member
    resources :room_reservations, only: [:new, :create, :show] do
      get 'confirm', on: :collection
    end
  end
  resources :room_reservations, only: [:index] do
    resources :ratings, only: [:create, :index]
    collection do
      get :index_admin
      get :show_admin
      get :actives
    end
    member do
      post :cancel_admin
      post :cancel
      post :make_check_in
      post :make_check_out
    end
  end
  resources :ratings, only: [:show] do
    get :index_admin, on: :collection
    get :show_admin, on: :member
    resources :review_responses, only: [:create]
  end
  resources :advanced_searches, only: [:index] do
    get :search, on: :collection
  end

  namespace :api do
    namespace :v1 do
      resources :inns, only: [:index, :show] do
        resources :rooms, only: [:index]
        get :search, on: :collection
      end
      resources :rooms, only: [] do
        resources :room_reservations, only: [] do
          get :available, on: :collection
        end
      end
    end
  end
end

app/models/inn.rb
class Inn < ApplicationRecord
  belongs_to :admin
  has_many :rooms
  has_many :room_reservations, through: :rooms
  has_many :ratings, through: :room_reservations
  has_many_attached :inn_photos

  validates :brand_name, :corporate_name, :registration_number, :phone,
            :email, :address, :neighborhood, :state, :city, :zip_code, :description,
            :payment_methods, :usage_policies, :check_in, :check_out, presence: true
  validates :accepts_pets, inclusion: { in: [true, false] }
  validates :registration_number, uniqueness: true
  validate :cnpj_is_valid?

  enum status: { inactive: 0, active: 5 }

  def full_description
    "#{self.corporate_name} - #{self.registration_number}"
  end

  scope :search_for_inns, ->(term) do
    where('inns.neighborhood LIKE ? OR inns.city LIKE ? OR inns.brand_name LIKE ?', "%#{term}%", "%#{term}%", "%#{term}%")
  end

  private

  def cnpj_is_valid?
    if CNPJ.valid?(self.registration_number).nil?
      errors.add(:registration_number, 'inválido')
    end
  end
end

app/controllers/api/v1/inns_controller.rb
class Api::V1::InnsController < Api::V1::ApiController
  def index
    inns = Inn.active
    render status: 200, json: inns
  end

  def search
    result_of_search = params[:query]
    inns = Inn.active.where('brand_name LIKE ?', "%#{result_of_search}%")
    render status: 200, json: inns
  end

  def show
    inn = Inn.active.find(params[:id])
    render status: 200, json: inn.as_json(except: [:registration_number, :corporate_name])
  end
end

app/controllers/inns_controller.rb
class InnsController < ApplicationController
	before_action :authenticate_admin!, only: [:new, :create, :edit, :update]
  before_action :set_inn_and_check_admin, only: [:edit, :update, :active, :inactive, :admin_show, :delete_photo]
  before_action :check_admin_inn, only: [:new, :create]
  before_action :set_inn_rooms, only: [:show, :admin_show]
  def show
    @inn = Inn.find(params[:id])
    @rooms = @inn.rooms.available
    @ratings = @inn.ratings.order(created_at: :desc) if @inn.ratings.present?
  end

  def new
    @inn = Inn.new
  end

  def create
    @inn = Inn.new(inn_params)
    @inn.admin = current_admin
    if @inn.save
      return redirect_to @inn, notice: 'Pousada registrada com sucesso'
    end
    flash.now[:notice] = 'Pousada não foi registrada'
    render :new
  end

  def edit; end

  def update
    params[:inn][:inn_photos].each do |photo|
      @inn.inn_photos.attach(photo)
    end
    if @inn.update(inn_params)
      return redirect_to admin_show_inn_path(@inn), notice: 'Pousada atualizada com sucesso'
    end
    flash.now[:notice] = 'Pousada não atualizada'
    render :edit
  end

  def admin_show; end

  def search
    @term = params[:query]
    @inns = Inn.search_for_inns(@term).order(:brand_name)
  end

  def by_city
    @city = params[:city]
    @inns = Inn.where(city: @city).order(:brand_name)
  end

  def active
    @inn.active!
    redirect_to @inn, notice: 'Sua pousada está ativa'
  end

  def inactive
    @inn.inactive!
    redirect_to @inn, notice: 'Sua pousada está inativa'
  end

  def delete_photo
    photo_id = params[:photo_id]
    photo = @inn.inn_photos.find(photo_id)

    if photo.destroy
      return redirect_to admin_show_inn_path(@inn), notice: 'Foto excluída com sucesso.'
    end
    redirect_to admin_show_inn_path(@inn), notice: 'Não foi possível excluir a foto.'
  end

  private

  def set_inn_rooms
    @inn = Inn.find(params[:id])
    if @inn.admin != current_admin
      @rooms = Room.available
    else
      @rooms = @inn.rooms
    end
  end

  def check_admin_inn
    return redirect_to root_path if current_admin.inn.present?
  end

  def set_inn_and_check_admin
    @inn = Inn.find(params[:id])
    if @inn.admin != current_admin
      redirect_to root_path, notice: 'Você não é dono dessa pousada'
    end
  end

  def inn_params
    params.require(:inn).permit(:brand_name,
                                :corporate_name,
                                :registration_number,
                                :phone,
                                :email,
                                :address,
                                :neighborhood,
                                :state,
                                :city,
                                :zip_code,
                                :description,
                                :payment_methods,
                                :accepts_pets,
                                :usage_policies,
                                :check_in,
                                :check_out)
  end
end

app/views/inns/_form.html.erb
<%= form_with(model: @inn) do |f| %>
  <div>
    <%= f.label :brand_name %>
    <%= f.text_field :brand_name %>
  </div>
  <div>
    <%= f.label :corporate_name %>
    <%= f.text_field :corporate_name %>
  </div>
  <div>
    <%= f.label :registration_number %>
    <%= f.text_field :registration_number %>
  </div>
  <div>
    <%= f.label :phone %>
    <%= f.telephone_field :phone %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
    <div>
    <%= f.label :address %>
    <%= f.text_field :address %>  
  </div>
  <div>
    <%= f.label :state %>
    <%= f.text_field :state %>
  </div>
    <div>
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>
  <div>
    <%= f.label :neighborhood %>
    <%= f.text_field :neighborhood %>
  </div>
  <div>
    <%= f.label :zip_code %>
    <%= f.text_field :zip_code %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div>
    <%= f.label :payment_methods %>
    <%= f.text_field :payment_methods %>
  </div>
  <div>
    <%= label_tag 'Aceita Pets?' %>
    <%= f.radio_button :accepts_pets, true %>
    <%= f.label :accepts_pets_true%>
    <%= f.radio_button :accepts_pets, false %>
    <%= f.label :accepts_pets_false %>
  </div>
  <div>
    <%= f.label :usage_policies %>
    <%= f.text_field :usage_policies %>
  </div>
  <div>
    <%= f.label :check_in %>
    <%= f.time_field :check_in %>

    <%= f.label :check_out %>
    <%= f.time_field :check_out %>
  </div>

  <% if action_name == 'edit' %>
    <div>
      <%= f.label :inn_photos, 'Adicionar Fotos' %>
      <%= f.file_field :inn_photos, multiple: true %>
    </div>
  <% end %>

  <%= f.submit 'Salvar' %>
<% end %>

app/views/inns/_inn.html.erb
<h2><%= @inn.brand_name %></h2>
<h3><%= @inn.full_description if @inn.admin == current_admin %></h3>

<div class="row">
  <% @inn.inn_photos.each do |photo| %>
    <div class="col-md-4">
      <%= image_tag photo, class: 'img-fluid rounded' %>
      <% if current_admin == @inn.admin %>
        <%= button_to "Excluir", delete_photo_inn_path(id: @inn.id, photo_id: photo.id), method: :delete, class:"btn btn-danger" %>
      <% end %>
    </div>
  <% end %>
</div>

<div>
  <dl>
    <dt>Bairro:</dt>
    <dd><%= @inn.neighborhood %></dd>
  </dl>
  <p><%= @inn.address %>, <%= @inn.city %>, CEP <%= @inn.zip_code %> - <%= @inn.state %></p>
</div>
<div>
  <p><%= @inn.description %></p>
  <dl>
    <dt><%= Inn.human_attribute_name('usage_policies') %></dt>
    <dd><%= @inn.usage_policies %></dd>
    <dt><%= Inn.human_attribute_name('payment_methods') %>:</dt>
    <dd><%= @inn.payment_methods %></dd>
    <dt><%= Inn.human_attribute_name('check_in') %>:</dt>
    <dd><%= @inn.check_in.strftime('%H:%M') %></dd>
    <dt><%= Inn.human_attribute_name('check_out') %>:</dt>
    <dd><%= @inn.check_out.strftime('%H:%M') %></dd>
    <dt><%= Inn.human_attribute_name('accepts_pets') %>:</dt>
    <dd><%= Inn.human_attribute_name("accepts_pets_#{@inn.accepts_pets?}") %></dd>
  </dl>
</div>

<div>
  <dt><%= Inn.human_attribute_name('email') %>:</dt>
  <dd><%= @inn.email %></dd>
  <dt><%= Inn.human_attribute_name('phone') %>:</dt>
  <dd><%= @inn.phone %></dd>
</div>

<h3>Quartos da <%= @inn.brand_name %></h3>

<%= render partial: 'rooms/rooms', locals: { rooms: @rooms } %>

<% if @ratings.present? %>
  <div>
  <dt>Nota Média:</dt>
  <dd><%= @inn.average_rating.ceil(1) %></dd>
  <h3>Últimas avaliações</h3>
  <% @ratings.limit(3).each do |rating| %>
    <%= render partial: 'ratings/rating', locals: {rating: rating} %>
  <% end %>
  </div>
  <% if @ratings.count > 3 %>
    <%= link_to 'Ver todas as avaliações', inn_ratings_path(inn_id: @inn.id) %>
  <% end %>
<% end %>

app/views/inns/admin_show.html.erb
<%= render 'inn' %>

<div>
  <% if @inn.inactive? %>
    <%= button_to 'Tornar Ativa', active_inn_path(@inn.id) %>
  <%  else %>
    <%= button_to 'Tornar Inativa', inactive_inn_path(@inn.id) %>
  <% end %>
</div>

<div>
  <div>
    <%= link_to 'Adicionar novo quarto', new_inn_room_path(inn_id: @inn.id) %>
  </div>
</div>

<div>
  <%= link_to 'Editar', edit_inn_path(@inn.id) %>
</div>

<div>
  <%= link_to 'Voltar', root_path %>
</div>

app/views/inns/by_city.html.erb
<h2>Pousadas de <%= @city %></h2>
<div class="list-group">
  <%= render partial: 'shared/inns', locals: { inns: @inns } %>
</div>

app/views/inns/edit.html.erb
<h1>Editando Pousada <%= @inn.brand_name %></h1>

<%= render 'form' %>

app/views/inns/new.html.erb
<h1>Nova Pousada</h1>

<% if @inn.errors.any? %>
  <% @inn.errors.full_messages.each do |message| %>
    <ul>
      <li><%= message %></li>
    </ul>
  <% end %>
<% end %>

<%= render 'form' %>

app/views/inns/search.html.erb
<% if @inns.present? %>
  <h2>Resultados da busca por <%= @term %></h2>
  <p><%= @inns.count %> <%= Inn.model_name.human(count: @inns.count).downcase %> <%= t(:found, count: @inns.count) %></p>
  <div class="list-group">
    <%= render partial: 'shared/inns', locals: { inns: @inns } %>
  </div>

<% else %>
  <h2>Nenhum resultado para <%= @term %></h2>
<% end %>

app/views/inns/show.html.erb
<%= render 'inn' %>