config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admins
  root "home#index"
  get 'city/:city' => 'inns#by_city', as: 'by_city'
  resources :inns, only: [:show, :new, :create, :edit, :update] do
    delete 'delete_photo/:photo_id', to: 'inns#delete_photo', as: 'delete_photo', on: :member
    resources :ratings, only: [:index]
    get :search, on: :collection
    resources :rooms, only: [:show, :new, :create, :edit, :update] do
      resources :price_customizations, only: [:new, :create, :edit, :update]
      post :available, on: :member
      post :unavailable, on: :member
    end
    post :active, on: :member
    post :inactive, on: :member
    get :admin_show, on: :member
  end
  resources :rooms, only: [:index] do
    delete 'delete_photo/:photo_id', to: 'rooms#delete_photo', as: 'delete_photo', on: :member
    resources :room_reservations, only: [:new, :create, :show] do
      get 'confirm', on: :collection
    end
  end
  resources :room_reservations, only: [:index] do
    resources :ratings, only: [:create, :index]
    collection do
      get :index_admin
      get :show_admin
      get :actives
    end
    member do
      post :cancel_admin
      post :cancel
      post :make_check_in
      post :make_check_out
    end
  end
  resources :ratings, only: [:show] do
    get :index_admin, on: :collection
    get :show_admin, on: :member
    resources :review_responses, only: [:create]
  end
  resources :advanced_searches, only: [:index] do
    get :search, on: :collection
  end

  namespace :api do
    namespace :v1 do
      resources :inns, only: [:index, :show] do
        resources :rooms, only: [:index]
        get :search, on: :collection
      end
      resources :rooms, only: [] do
        resources :room_reservations, only: [] do
          get :available, on: :collection
        end
      end
    end
  end
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :inn
  has_many :price_customizations
  has_many :room_reservations
  has_many_attached :room_photos

  enum for_reservations: { available: 0, unavailable: 5 }

  validates :title, :description, :dimension, :max_occupancy, :daily_rate, presence: true

  def current_price_customization
    date_current_customized = price_customizations.find_by('start_date <= ? AND end_date >= ?', Date.today, Date.today)
    if date_current_customized.present?
      date_current_customized
    end
  end

  def total_price(check_in, check_out)
    total_price = 0

    (check_in..check_out).each do |date|
        daily_rate = current_daily_rate(date: date)
        total_price += daily_rate
    end

    total_price
  end

  def current_daily_rate(date: Date.today)
    date_customization = price_customizations.find_by('start_date <= ? AND end_date >= ?', date, date)
    return date_customization.daily_rate if date_customization.present?
    daily_rate
  end
end

app/controllers/api/v1/rooms_controller.rb
class Api::V1::RoomsController < Api::V1::ApiController
  def index
    inn = Inn.active.find(params[:inn_id])
    rooms = inn.rooms.available
    render status: 200, json: rooms
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :check_admin, only: [:edit, :update, :new, :create, :available, :unavailable]
  before_action :set_room, only: [:show, :edit, :update, :available, :unavailable, :delete_photo]
  def index
    @rooms = Room.available
  end

  def show
    @inn = Inn.find(params[:inn_id])
    @price_customizations = @room.price_customizations
    if @inn.admin != current_admin && @room.unavailable?
      redirect_to root_path, notice: "Quarto #{@room.title} está desabilitado para reservas"
    end
  end

  def new
    @inn = Inn.find(params[:inn_id])
    @room = Room.new
  end

  def create
    @inn = Inn.find(params[:inn_id])
    @room = @inn.rooms.new(room_params)

    if @room.save
      return redirect_to @inn, notice: 'Quarto registrado com sucesso'
    end
    flash.now[:notice] = 'Quarto não foi registrado'
    render :new
  end

  def edit ;end

  def update
    params[:room][:room_photos].each do |photo|
      @room.room_photos.attach(photo)
    end
    if @room.update(room_params)
      return redirect_to [@inn, @room], notice: 'Quarto atualizado com sucesso'
    end
    flash.now[:notice] = 'Quarto não foi atualizado'
    render :new
  end

  def available
    @room.available!
    redirect_to [@inn, @room], notice: 'Quarto habilitado para reservas'
  end

  def unavailable
    @room.unavailable!
    redirect_to [@inn, @room], notice: 'Quarto desabilitado para reservas'
  end

  def delete_photo
    return redirect_to root_path if current_admin != @room.inn.admin
    photo_id = params[:photo_id]
    photo = @room.room_photos.find(photo_id)

    if photo.destroy
      return redirect_to inn_room_path(inn_id: @room.inn.id, id: @room.id), notice: 'Foto excluída com sucesso.'
    end
    redirect_to inn_room_path(inn_id: @room.inn.id, id: @room.id), notice: 'Não foi possível excluir a foto.'
  end

  private

  def set_room
    @room = Room.find(params[:id])
  end

  def check_admin
    @inn = Inn.find(params[:inn_id])
    if @inn.admin != current_admin
      redirect_to root_path, notice: 'Você não possui acesso a pousada responsável'
    end
  end

  def room_params
    params.require(:room).permit(:title,
                                :description,
                                :dimension,
                                :max_occupancy,
                                :daily_rate,
                                :private_bathroom,
                                :balcony,
                                :air_conditioning,
                                :tv,
                                :wardrobe,
                                :safe_available,
                                :accessible_for_disabled)
  end
end

app/views/rooms/_form.html.erb
<%= form_with(model: [@inn, @room]) do |f| %>
 <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div>
    <%= f.label :dimension %>
    <%= f.number_field :dimension %>
  </div>
  <div>
    <%= f.label :max_occupancy %>
    <%= f.number_field :max_occupancy %>
  </div>
  <div>
    <%= f.label :daily_rate %>
    <%= f.number_field :daily_rate %>
  </div>
  <div>
  	<div>
      <%= f.label :private_bathroom %>
      <%= f.check_box :private_bathroom, {}, true %>
    </div>
    <div>
      <%= f.label :balcony %>
      <%= f.check_box :balcony, {}, true %>
    </div>
    <div>
      <%= f.label :air_conditioning %>
      <%= f.check_box :air_conditioning, {}, true %>
    </div>
    <div>
      <%= f.label :tv %>
      <%= f.check_box :tv, {}, true %>
    </div>
    <div>
      <%= f.label :wardrobe %>
      <%= f.check_box :wardrobe, {}, true %>
    </div>
    <div>
    <%= f.label :safe_available %>
    <%= f.check_box :safe_available, {}, true %>
      </div>
    <div>
      <%= f.label :accessible_for_disabled %>
      <%= f.check_box :accessible_for_disabled, {}, true %>
    </div>
    <div>
      <%= f.label :room_photos, 'Adicionar Fotos' %>
      <%= f.file_field :room_photos, multiple: true %>
    </div>
  </div>
  <%= f.submit 'Salvar' %>
<% end %>

app/views/rooms/_price_customization.html.erb
<% if room.current_price_customization %>
  <p>
    <%= t(room.current_price_customization.season) %> de 
    <%= room.current_price_customization.season_name %>
  </p>
<% end %>

<p>A partir de R$ <%= room.current_daily_rate %>,00</p> 

app/views/rooms/_room.html.erb
<h1><%= @room.title %></h1>

<div class="row">
  <% @room.room_photos.each do |photo| %>
    <div class="col-md-4">
      <%= image_tag photo, class: 'img-fluid rounded' %>
      <% if current_admin == @room.inn.admin %>
        <%= button_to "Excluir", delete_photo_room_path(id: @room.id, photo_id: photo.id), method: :delete, class:"btn btn-danger" %>
      <% end %>
    </div>
  <% end %>
</div>

<p><%= @room.description %></p>

<ul>
  <li><strong>Área do Quarto:</strong> <%= @room.dimension %>m²</li>
  <li><strong>Capacidade Máxima:</strong> <%= @room.max_occupancy %> pessoas</li>
  <li><strong>Diária Padrão:</strong> R$ <%= @room.daily_rate %>,00</li>
  <li><%= Room.human_attribute_name('private_bathroom') if @room.private_bathroom? %></li>
  <li><%= Room.human_attribute_name('balcony') if @room.balcony? %></li>
  <li><%= Room.human_attribute_name('air_conditioning') if @room.air_conditioning?  %></li>
  <li><%= Room.human_attribute_name('tv') if @room.tv?  %></li>
  <li><%= Room.human_attribute_name('wardrobe') if @room.wardrobe? %></li>
  <li><%= Room.human_attribute_name('safe_available') if @room.safe_available? %></li>
  <li><%= Room.human_attribute_name('accessible_for_disabled') if @room.accessible_for_disabled?%></li>
</ul>

app/views/rooms/_rooms.html.erb
<% if rooms.any? %>
  <div class="list-group">
    <% rooms.each do |room| %>
      <%= link_to inn_room_path(id: room.id, inn_id: room.inn.id), class: "list-group-item list-group-item-action" do %>
        <div class="d-flex w-100 justify-content-between">
          <% if room.room_photos.present? %>
            <%= image_tag room.room_photos.first, style: 'width: 200px' %>
          <% end %>
          <h5 class="mb-1"><%= room.title %></h5>
          <small>Área do Quarto: <%= room.dimension %>m²</small>
        </div>
        <p class="mb-1"><%= room.description %></p>
        <small>Ocupação Máxima: <%= room.max_occupancy %></small>
      <% end %>
    <% end %>
  </div>
<% else %>
  <p>Não há quartos disponíveis</p>
<% end %>

app/views/rooms/edit.html.erb
<h1>Editar <%= @room.title %></h1>

<%= render 'form' %>

app/views/rooms/index.html.erb
<h1>Quartos Disponíveis</h1>

<%= render partial: 'rooms', locals: { rooms: @rooms } %>

app/views/rooms/new.html.erb
<h1>Novo Quarto</h1>

<% if @room.errors.any? %>
  <% @room.errors.full_messages.each do |message| %>
    <ul>
      <li><%= message %></li>
    </ul>
  <% end %>
<% end %>

<%= render 'form' %>

app/views/rooms/show.html.erb
<%= render 'room' %>

<div>
  <%= link_to 'Reservar', new_room_room_reservation_path(room_id: @room.id) %>
</div>

<p><%= t(@room.for_reservations) %> para reservas</p>
<% if @inn.admin == current_admin %>
  <%= render partial: 'rooms/price_customization', locals: { room: @room } %>
<% end %>

<% if @room.inn.admin == current_admin %>
  <%= link_to 'Editar', edit_inn_room_path(inn_id: @room.inn.id) %>

  <div>
    <% if @room.unavailable? %>
      <%= button_to 'Habilitar reserva', available_inn_room_path(inn_id: @room.inn.id , id: @room.id) %>
      <p>Quarto indisponível para nova reserva</p>
    <% else %>
      <p>Quarto disponível para nova reserva</p>
      <%= button_to 'Desabilitar reserva', unavailable_inn_room_path(inn_id: @room.inn.id, id: @room.id) %>
    <% end %>
  </div>

  <div>
    <h3><%= PriceCustomization.model_name.human(count: @room.price_customizations.count) %></h3>
    <% @price_customizations.each do |price_customization| %>
      <div>
        <%= link_to edit_inn_room_price_customization_path(inn_id: @room.inn.id,
                                                          room_id: @room.id,
                                                          id: price_customization.id) do %>
          <p>
            <%= price_customization.season_name %>
          </p>
        <% end %>
        <p>
          De <%= l(price_customization.start_date) %> a <%= l(price_customization.end_date) %>,
          a partir de <%= price_customization.daily_rate %>
        </p>
      </div>
    <% end %>
    <%= link_to 'Adicionar personalização preço', new_inn_room_price_customization_path(inn_id: @room.inn.id , room_id: @room.id) %>
  </div>
<% end %>