config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admins
  root "home#index"
  get 'city/:city' => 'inns#by_city', as: 'by_city'
  resources :inns, only: [:show, :new, :create, :edit, :update] do
    delete 'delete_photo/:photo_id', to: 'inns#delete_photo', as: 'delete_photo', on: :member
    resources :ratings, only: [:index]
    get :search, on: :collection
    resources :rooms, only: [:show, :new, :create, :edit, :update] do
      resources :price_customizations, only: [:new, :create, :edit, :update]
      post :available, on: :member
      post :unavailable, on: :member
    end
    post :active, on: :member
    post :inactive, on: :member
    get :admin_show, on: :member
  end
  resources :rooms, only: [:index] do
    delete 'delete_photo/:photo_id', to: 'rooms#delete_photo', as: 'delete_photo', on: :member
    resources :room_reservations, only: [:new, :create, :show] do
      get 'confirm', on: :collection
    end
  end
  resources :room_reservations, only: [:index] do
    resources :ratings, only: [:create, :index]
    collection do
      get :index_admin
      get :show_admin
      get :actives
    end
    member do
      post :cancel_admin
      post :cancel
      post :make_check_in
      post :make_check_out
    end
  end
  resources :ratings, only: [:show] do
    get :index_admin, on: :collection
    get :show_admin, on: :member
    resources :review_responses, only: [:create]
  end
  resources :advanced_searches, only: [:index] do
    get :search, on: :collection
  end

  namespace :api do
    namespace :v1 do
      resources :inns, only: [:index, :show] do
        resources :rooms, only: [:index]
        get :search, on: :collection
      end
      resources :rooms, only: [] do
        resources :room_reservations, only: [] do
          get :available, on: :collection
        end
      end
    end
  end
end

app/models/room_reservation.rb
class RoomReservation < ApplicationRecord
  belongs_to :room
  belongs_to :user
  has_one :rating

  validates :check_in, :check_out, :number_of_guests, :total_daily_rates, :code, presence: true
  validate :unavailable_for_date?, on: [:create, :confirm]
  validate :guest_limit, :check_out_is_later

  before_validation :total_daily_rates_to_reserve
  before_validation :generate_code, on: :create
  after_save :guest_arrival_when_check_in
  after_save :guest_departure_when_check_out

  enum status: { canceled: 0, pending: 5, active: 10, closed: 15 }

  def unavailable_for_date?
    room_reservations = self.room.room_reservations.where('? <= check_out AND ? >= check_in', self.check_in, self.check_out)
                                                  .where.not(status: :canceled)

    if room_reservations.present?
      self.errors.add(:base, "Reserva não disponível entre #{I18n.l(check_in.to_date)} e #{I18n.l(check_out.to_date)}")
    end
  end

  def guest_limit
    if self.room.present? && self.number_of_guests.present? && self.number_of_guests > self.room.max_occupancy
      self.errors.add(:number_of_guests, "não pode ser maior do que #{self.room.max_occupancy} pessoas")
    end
  end

  def less_than_7_days_to_check_in?
    days_remaining_to_check_in = self.check_in - Date.today
    days_remaining_to_check_in < 7
  end

  def reservation_if_check_in
    Date.today >= self.check_in
  end

  def two_days_late_for_check_in?
    days_of_delay = Date.today - self.check_in
    days_of_delay >= 2
  end

  def guest_departure_when_check_out
    if status == 'closed' && guest_departure.nil? && guest_arrival.present?
      self.update(guest_departure: Time.zone.now, paid: room.total_price(guest_arrival.to_date, Time.zone.now))
    end
  end

  private

  def check_out_is_later
    if self.check_in.present? && self.check_out.present? && self.check_in > self.check_out
      self.errors.add(:base, 'O Check in deve ser menor que o Check out')
    end
  end

  def guest_arrival_when_check_in
    if status == 'active' && guest_arrival.nil?
      update(guest_arrival: Time.current)
    end
  end

  def generate_code
    self.code = SecureRandom.alphanumeric(8).upcase
  end

  def total_daily_rates_to_reserve
    if check_in.present? && check_out.present?
      return self.total_daily_rates = self.room.total_price(self.check_in, self.check_out)
    end
  end
end

app/controllers/api/v1/room_reservations_controller.rb
class Api::V1::RoomReservationsController < Api::V1::ApiController
  def available
    room = Room.find(params[:room_id])

    check_in = Date.parse(params[:check_in]) if params[:check_in].present?
    check_out = Date.parse(params[:check_out]) if params[:check_out].present?

    number_of_guests = params[:number_of_guests]

    if check_in.blank? || check_out.blank? || number_of_guests.blank?
      return render status: 400, json: { "info": "Preencha todos os campos corretamente" }
    end

    total_daily_rates = room.total_price(check_in, check_out)
    room_reservation = room.room_reservations.build(check_in: check_in, check_out: check_out)
    render status: 200, json: reservation_available(room_reservation, total_daily_rates)
  end

  def reservation_available(room_reservation, total_daily_rates)
    if room_reservation.unavailable_for_date?
      return { "status": "não disponível", "info": "O quarto não está disponível para as datas solicitadas." }
    end

    {
      "status": "disponível",
      "total": total_daily_rates
    }
  end
end

app/controllers/room_reservations_controller.rb
class RoomReservationsController < ApplicationController
  before_action :set_room, only: [:show_admin, :new, :confirm, :create, :show]
  before_action :authenticate_user!, only: [:create, :index, :show]
  before_action :set_room_reservation, only: [:show, :cancel, :show_admin, :make_check_in, :cancel_admin, :make_check_out]
  before_action :authenticate_admin!, only: [:index_admin, :show_admin, :actives]
  def index_admin
    @room_reservations = current_admin.inn.room_reservations
  end

  def index
    @room_reservations = current_user.room_reservations
  end

  def actives
    @room_reservations = current_admin.inn.room_reservations.active
  end

  def show_admin; end

  def new
    @room_reservation = RoomReservation.new
  end

  def confirm
    @check_in = params[:check_in]
    @check_out = params[:check_out]
    @number_of_guests = params[:number_of_guests]
    @total_daily_rates = @room.total_price(@check_in, @check_out)
    @room_reservation = @room.room_reservations.build(check_in: @check_in, check_out: @check_out)
    return render :new if @room_reservation.unavailable_for_date?
    unless @check_in.present? || @check_out.present? || @number_of_guests.present?
      flash.now[:alert] = 'Preencha todos os campos corretamente'
      return render :new
    end
  end

  def create
    @room_reservation = @room.room_reservations.build(room_reservation_params)
    @room_reservation.user = current_user
    @room_reservation.save!
    redirect_to room_reservations_path, notice: "Nova reserva registrada"
  end

  def show
    @rating = Rating.new
  end

  def cancel
    if @room_reservation.user != current_user || @room_reservation.less_than_7_days_to_check_in?
      return redirect_to root_path, notice: 'Você não tem permisão para concluir esta ação'
    end
    @room_reservation.canceled!
    redirect_to room_reservations_path, notice: 'Reserva cancelada com sucesso'
  end

  def cancel_admin
    unless @room_reservation.room.inn.admin == current_admin && @room_reservation.two_days_late_for_check_in?
      return redirect_to root_path, notice: 'Você não tem permisão para concluir esta ação'
    end
    @room_reservation.canceled!
    redirect_to index_admin_room_reservations_path, notice: 'Reserva cancelada com sucesso'
  end

  def make_check_in
    unless @room_reservation.room.inn.admin == current_admin && @room_reservation.reservation_if_check_in
      return redirect_to root_path, notice: 'Você não tem permisão para concluir esta ação'
    end
    @room_reservation.active!
    redirect_to show_admin_room_reservations_path(room_id: @room_reservation.room.id, id: @room_reservation.id),
                notice: 'Reserva ativa com sucesso'
  end

  def make_check_out
    unless @room_reservation.room.inn.admin == current_admin && @room_reservation.active?
      return redirect_to root_path, notice: 'Você não tem permisão para concluir esta ação'
    end
    @room_reservation.update(chosen_payment_method: params[:chosen_payment_method])
    @room_reservation.closed!
    redirect_to show_admin_room_reservations_path(room_id: @room_reservation.room.id, id: @room_reservation.id),
                notice: 'Reserva finalizada com sucesso'
  end

  private

  def set_room_reservation
    @room_reservation = RoomReservation.find(params[:id])
  end

  def set_room
    @room = Room.find(params[:room_id])
  end

  def room_reservation_params
    params.require(:room_reservation).permit(:check_in,
                                            :check_out,
                                            :number_of_guests)
  end
end

app/views/room_reservations/_room_reservation.html.erb
<h5><%= @room.inn.brand_name %></h5>
<h6><%= @room.title %></h6>
<p>
  <%= RoomReservation.human_attribute_name('check_in') %>: <%= l(check_in) %> <%= @room.inn.check_in.strftime('%H:%M') %>
</p>
<p>
  <%= RoomReservation.human_attribute_name('check_out') %>: <%= l(check_out) %> <%= @room.inn.check_out.strftime('%H:%M') %>
</p>
<p><%= Inn.human_attribute_name('payment_methods') %>: <%= @room.inn.payment_methods %>></p>
<p><%= RoomReservation.human_attribute_name('number_of_guests') %>: <%= number_of_guests %></p>

app/views/room_reservations/_room_reservations_admin.html.erb
<div>
  <% if @room_reservations.any? %>
    <% @room_reservations.each do |reservation| %>
      <%= link_to show_admin_room_reservations_path(room_id: reservation.room.id, id: reservation.id) do %>
        <%= reservation.code %>
        <%= reservation.room.title %>
        <p>Total: <%= reservation.total_daily_rates %></p>
      <% end %>
    <% end %>
  <% else %>
    <p>Não há reservas</p>
  <% end %>
</div>

app/views/room_reservations/actives.html.erb
<h1>Reservas Ativas</h1>

<%=  render 'room_reservations_admin' %>

app/views/room_reservations/confirm.html.erb
<h1>Informações Sobre Sua Reserva</h1>

<h4>Preço total de diárias: <%= @total_daily_rates %></h4>

<% if user_signed_in? %>
  <%= render partial: 'room_reservation', locals: { check_in: Date.parse(@check_in),
                                                    check_out: Date.parse(@check_out),
                                                    number_of_guests: @number_of_guests } %>
<% end %>
<%= form_with(model: [@room, @room_reservation]) do |f| %>
  <%= f.hidden_field :check_in, value: @check_in %>
  <%= f.hidden_field :check_out, value: @check_out %>
  <%= f.hidden_field :number_of_guests, value: @number_of_guests %>
  <%= f.submit 'Confirmar Reserva' %>
<% end %>

<p>caso saia as informações serão perdidas</p>

app/views/room_reservations/index.html.erb
<h1>Minhas Reservas</h1>

<div>
  <% @room_reservations.each do |reservation| %>
    <%= link_to reservation.room.title, room_room_reservation_path(room_id: reservation.room.id, id: reservation.id) %>
    <p>Total: <%= reservation.total_daily_rates %></p>
  <% end %>
</div>

app/views/room_reservations/index_admin.html.erb
<h1>Reservas</h1>

<%=  render 'room_reservations_admin' %>

app/views/room_reservations/new.html.erb
<% if @room_reservation.errors.any? %>
  <div id="error_explanation">
    <ul>
      <% @room_reservation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= render 'rooms/room' %>

<h2>Faça uma Reserva</h2>

<%= form_with(url: confirm_room_room_reservations_path(room_id: @room.id), method: :get) do |f| %>
  <div>
    <%= f.label :check_in, autofocus: true %>
    <%= f.date_field :check_in %>
  </div>
  <div>
    <%= f.label :check_out %>
    <%= f.date_field :check_out %>
  </div>
  <div>
    <%= f.label :number_of_guests, 'Quantidade de Hóspedes' %>
    <%= f.number_field :number_of_guests %>
  </div>

  <%= f.submit 'Salvar' %>
<% end %>

app/views/room_reservations/show.html.erb
<h1>Reserva: <%= @room_reservation.code %></h1>

<%= render partial: 'room_reservation', locals: { check_in: @room_reservation.check_in, 
	                                                check_out: @room_reservation.check_out,
	                                                number_of_guests: @room_reservation.number_of_guests } %>
<p>Total: <%= @room_reservation.total_daily_rates %></p>

<% if @room_reservation.pending? && !@room_reservation.less_than_7_days_to_check_in? %>
  <%= button_to 'Cancelar', cancel_room_reservation_path(@room_reservation.id) %>
<% end %>

<% if @room_reservation.closed? && @rating.nil? %>

  <h2>Avalie sua estadia</h2>

  <%= form_with(model: [@room_reservation, @rating]) do |f| %>
    <div>
      <%= f.label :grade %>
      <%= f.select(:grade, [1, 2, 3, 4, 5]) %>
    </div>
    <div>
      <%= f.label :comment %>
      <%= f.text_area :comment %>
    </div>

    <%= f.submit 'Enviar' %>
  <% end %>
<% end %>


<%= link_to 'Sua avaliação', rating_path(@room_reservation.id) if @rating.present? %>

app/views/room_reservations/show_admin.html.erb
<h3>Reserva: <%= @room_reservation.code %></h3>
<p>Status: <%= t(@room_reservation.status) %></p>

<% if @room_reservation.active? %>
  <p>
    Valor do dia atual:
    <%= @room_reservation.room.total_price(@room_reservation.guest_arrival.to_date, Date.current) %>
  </p>
<% end %>

<% if @room_reservation.guest_arrival %>
  <p>Check in realizado em: <%= localize(@room_reservation.guest_arrival, format: '%d/%m/%Y %H:%M') %></p>
<% end %>

<% if @room_reservation.closed? %>
  <p>Total pago: <%= @room_reservation.paid %></p>
  <p>Check out realizado em: <%= localize(@room_reservation.guest_departure, format: '%d/%m/%Y %H:%M') %></p>
  <p><%= RoomReservation.human_attribute_name('chosen_payment_method') %>: <%= @room_reservation.chosen_payment_method %></p>
<% end %>

<p>Hóspede: <%= @room_reservation.user.name %></p>
<h3>Previsões</h3>
<%= render partial: 'room_reservation', locals: { check_in: @room_reservation.check_in,
                                                  check_out: @room_reservation.check_out,
                                                  number_of_guests: @room_reservation.number_of_guests } %>

<% if @room_reservation.pending? %>
  <% if @room_reservation.reservation_if_check_in %>
    <%= button_to 'Fazer check in', make_check_in_room_reservation_path(@room_reservation.id) %>
  <% end %>

  <% if @room_reservation.pending? && @room_reservation.two_days_late_for_check_in? %>
    <%= button_to 'Cancelar', cancel_admin_room_reservation_path(@room_reservation.id) %>
  <% end %>
<% end %>

<% if @room_reservation.active? %>
  <h3>Realizar check out</h3>
  <%= form_with(url: make_check_out_room_reservation_path(@room_reservation.id)) do |f| %>
    <div>
      <%= f.label :chosen_payment_method, RoomReservation.human_attribute_name('chosen_payment_method') %>
      <%= f.text_field :chosen_payment_method %>
    </div>
    <%= f.submit 'Fazer check out' %>
  <% end %>
<% end %>